### PR TITLE
added timeout

### PR DESCRIPTION
**Pull request by workingDog**
Added client wide timeout (in seconds) to NetworkingClient(baseURL: String, timeout: TimeInterval? = nil).
To customise a specific request, just set, client.timeout = 15, before your request.

### CODE REVIEW

**Comment by s4cha** [comment]
Will review this next week, can't wait to try it out :)

**Comment by s4cha** [comment]
I see you added parse-error relate code, let me know when I can try it out.

**Comment by workingDog** [comment]
Yes sorry, having 2 branches was getting out of sync for me, so I put everything back into master.

@ScratchMyTail seems to be happy with the latest code, so it can now be merged.
This "added timeout" PR includes all of the errors and jsonPayload fixes.

@s4cha please review the PR code, and merge if acceptable.

**Comment by s4cha** [comment]
Hey @workingDog, fantastic work here! Congrats.
Just a side note for next time, it's would be great to separate PRs for each feature, to keep them atomic and facilitate review.
Otherwise 💯 !

**Pull request merged**
