### PR TITLE
Allow Multiple Multipart Uploads

### LINKED ISSUE #4: Multipart uploads are limited to only one multipart section
There seem to be two limitations of the Multipart calls in this Networking library.

1. It looks like when using the multipart data in a request, the params get encoded into the URL. [^1]  This doesn't seem like standard behavior, I think it'd be more intuitive for the params to be encoded as additional multiparts (this is how HTML forms would handle it). [^2] [^3]

2. It looks like there's only support for one Multipart data object per request. It would be handy if the API could support multiple file uploads! [^4]

[^1]: https://github.com/freshOS/Networking/blob/master/Sources/Networking/NetworkingRequest.swift#L123-L125
[^2]: https://ec.haxx.se/http/http-multipart
[^3]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type
[^4]: https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

### PR DESCRIPTION
**Pull request by jeffbarg**
- Allow multiple MultipartData objects as part of one request

- Correctly upload params in a MultipartData request in the body as a body part [1]

Fixes #4

[1]: https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

### CODE REVIEW

**Comment by s4cha** [comment]
@jeffbarg This is very very cool. I should have time tomorrow to review this so I'll keep you posted
With tests! What's more to ask ! 💯

**Comment by s4cha** [comment]
On top of fixing an existing issue and adding a cool requested feature, the implementation is very clean and comes with tests. Fantastic job 🥇

**Comment by s4cha** [comment]
I am going to rename `HttpBodyConvertable` to `HttpBodyConvertible` as per `CustomStringConvertible` if you don't mind.

**Comment by jeffbarg** [comment]
Sorry for the typo 😅 Nice catch, thanks

**Pull request merged**
